### ISSUE TITLE
latest site doesn't build

### ISSUE THREAD

**Issue by northdpole** [OWASP/www-committee-outreach#2]
the error message is:
`

A file was included in /_layouts/col-sidebar.html that is a symlink or does not exist in your _includes directory.
`

seems we're missing the writers file and the _includes dir, it can be copied from:
https://github.com/OWASP/www-community/blob/master/_includes/writers.html

**Comment by kingthorin** [comment]
The error message is misleading. The problem was titles, lack of front matter, and tags. 
(The `writers.html` include in the `www-community` repo is really specific to that repo/content.)

Note in order to test locally you can setup pretty quickly on a kali or Ubuntu VM based on these details: https://github.com/OWASP/www-project-web-security-testing-guide/#getting-started (just use this repo instead of the www-project-web-security-testing-guide repo).
